dependencies:
  flutter:
    sdk: flutter
description: Helper utilities for Flutter projects.
dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
environment:
  flutter: '>=3.13.0'
  sdk: '>=3.1.0 <4.0.0'
flutter: null
name: flutter_helpers
version: 0.0.1
